Components:

  # Base implmentation is a local project
  - Type: local
    Implementations:
      - config
      - setting
      - security

  # Also use the local API for commands and orchestration
  - Type: local
    Implementations:
      - orchestrate
      - command
